### PR TITLE
Bump max supported NC version to 15

### LINKED ISSUE #62: Nextcloud 15 Compatibility
The Beta of Nextcloud 15 has started. It would be great if this draw.io app would be released for Nextcloud 15.

### PR DESCRIPTION
**Pull request by janLo**
This fixes #62

### CODE REVIEW

**Comment by Aschenbecher** [comment]
thx for your help! is it possible to change the max version to , for example 25, to be safe at future upgrades?

**Comment by janLo** [comment]
> thx for your help! is it possible to change the max version to , for example 25, to be safe at future upgrades?

I would not do this as sometimes changes in the app are needed as the API or the layout changes (see #53).

**Comment by janLo** [comment]
As I just realized, this PR duplicates #64

**Comment by Manfredzimmermann** [comment]
My Nextcloud is running at a service provider. I only have access to the web interface of Nextcloud. I can update Draw.io only on Webinterface with a button. When will the latest version of Draw.io for Nextcloud be released?

**Pull request merged**
