### PR TITLE
Rewrite file access to use the webdav interface

### PR DESCRIPTION
**Pull request by geiseri**
This is a pretty big set of changes, but I wanted to take the best parts of my javascript implementation and merge it with the best parts of your PHP.   My reasoning being that the webdav interface is very stable and requires less custom code that is arguably duplicated by way to many plugins.  I also prefer Javascript to make for a more reactive UI.  I also had a few features that were in my version that were missing from your version.

Without further delay here are the changes:

1. Use webdav interface to read and write files using the javascript client.
1. Removed unused PHP and Javascript code.
1. Use the normal UI to create the initial file on the filesystem and then open it up in the "template" mode in the editor.  This way we do not get into the debate of Letter vs A4 :)
1. Rename Drawio namespace to DrawIO.  Cosmetic and could go back if requested.
1. Convert ``$.get(...)`` methods to use promises
1. Change the popup window to a url redirect.  This was done for two reasons.  The first being that due to the json protocol having more than one diagram open at a time confuses the event handlers.  The second one is that by default a lot of browsers disable Javascript "popup" windows and this could be a non-obvious reason why the app will not work.
1. Have the editing diagram go back to the same folder and file selection view.
1. Added logic to keep the current urls interface.  It looks prettier than having ``?foo=bar&more=stuff``....
1. Set the loading of the ``iframe`` url until after everything has been hooked up with the draw.io api.  This eliminates any race conditions and allows for more opportunities to give user feedback.
1. Ran it through a json format tool to make the code standard consistent.

There are a lot of "TODO" comments in there around notification of errors to the user.  I am not really sure how many of them matter, but they need to be reviewed.  There is also a regression in that the mtime is no longer preserved/checked.  This could cause underlying modifications to be missed, but in the end I am not sure how much this matters.  The reasoning being that if the write fails, there is no real way to "Save as" from the drawio api.  The best we can do is save it locally and then upload it, or auto-rename it and notify the user via the ``dialog`` action.

Once this has been reviewed and ready for merge I will squash this so there are not so many extra commit messages.

### CODE REVIEW

**Comment by pawelrojek** [comment]
Thanks! Reviewing.

**Comment by geiseri** [comment]
@pawelrojek any feedback?

**Comment by pawelrojek** [comment]
Sorry for the delay.

The proposed changes seem reasonable. Nothing seems to be broken ;) I will merge your pull request and we will continue from here.

**Comment by pawelrojek** [comment]
Good job, BTW 👍 

I've bumped the version up to 0.8.7.

**Pull request merged**
