### PR TITLE
Add Nextcloud 14 compatibility

### LINKED ISSUE #47: Compatibility with Nextcloud 14
Hi,

as you may have already seen, we have entered the beta phase for the release of Nextcloud 14. We usually try to keep up compatibility with previous app versions, but in some cases apps need some adjustments to properly work on new Nextcloud releases. With Nextcloud 14 there have been quite some changes in that regard:

You can find a list of all critical changes for app developers and admins at https://github.com/nextcloud/server/issues/7827. You can run occ app:check-code to validate that there are no issues with deprecated or private message calls.

One critical change is the overall restructuring of the main template (https://github.com/nextcloud/server/pull/9982) that might require some adjustments in your app.

We would be very pleased if you can make your app compatible with Nextcloud 14 and release a new version to the app store, so that users can properly test it and the upgrade experience to Nextcloud 14 will be even better than before.

Feel free to ask, if you have any questions regarding making your app compatible with Nextcloud 14.

Thanks for being part of the Nextcloud community and for all the effort you put into providing this app :rocket: .

### PR DESCRIPTION
**Pull request by janLo**
This fixes the compatibility with Nextcloud 14 and resolves #47. 

Compatibility with older versions isn't tested but the only possible issue might be the change from a02f8a6.

### CODE REVIEW

**Comment by morph027** [comment]
Thank you!

**Comment by pawelrojek** [comment]
Thank you very much! 

I'm gonna look into possible backward compatibility issues and then decide how to proceed with the merge.

**Comment by TrinaryLogic** [comment]
I've been running this patch on Nextcloud 13.0.6 for about a week and haven't noticed any issues, everything looks the same as it always has.

**Comment by e-alfred** [comment]
@pawelrojek Can you package and upload a new version to apps.nextcloud.com?

**Comment by pawelrojek** [comment]
@e-alfred 
It will be available in an hour or so :)

**Pull request merged**
